import type { ProviderUserInfo } from '@/lib/providers'
import { defineAsyncComponent, ref } from 'vue'
import { useI18n } from '@/lib/locals'
import { defineProvider, useProviderSession } from '@/lib/providers'
import { useServiceStore } from '@/stores'

export const useAIHubMixProvider = defineProvider(() => {
  const { t } = useI18n({
    'zh-CN': {
      providerName: 'AIHubMix',
      description: '支持大部分主流模型',
      alipay: '支付宝',
    },
    'en-US': {
      providerName: 'AIHubMix',
      description: 'One Gateway, Infinite Models.',
      alipay: 'Alipay',
    },
  })
  const { proxy } = useServiceStore()

  const session = useProviderSession<{
    token: string
    session: string
  }>('aihubmix')

  const user = ref<null | ProviderUserInfo>()

  async function makeHeaders(requireSession: boolean, extra?: Record<string, string>) {
    const s = requireSession ? await session.get() : null
    if (requireSession && !s) {
      throw new Error('No session found')
    }
    return {
      'accept': 'application/json, text/plain, */*',
      'accept-language': 'zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6',
      'content-type': 'application/json',
      'priority': 'u=1, i',
      'sec-ch-ua': '"Microsoft Edge";v="141", "Not?A_Brand";v="8", "Chromium";v="141"',
      'sec-ch-ua-mobile': '?0',
      'sec-ch-ua-platform': '"Linux"',
      'sec-fetch-dest': 'empty',
      'sec-fetch-mode': 'cors',
      'sec-fetch-site': 'same-site',
      'Referer': 'https://console.aihubmix.com/',
      ...extra,
      ...(s
        ? {
            Cookie: `session=${s.session}`,
          }
        : {}),
    }
  }

  return {
    id: 'aihubmix',
    get name() {
      return t('providerName')
    },
    get description() {
      return t('description')
    },
    get logo() {
      return import.meta.resolve('./logo.png')
    },
    homepage: 'https://aihubmix.com/',

    get user() {
      return user.value
    },
    async refreshUser() {
      const s = await session.get()
      if (!s) {
        user.value = null
        return
      }

      const { ok, json } = await proxy('https://aihubmix.com/call/usr/self', {
        headers: await makeHeaders(true),
      })

      if (!ok || !json.success) {
        user.value = null
        return
      }

      user.value = {
        name: json.data.display_name,
        email: json.data.email,
        balance: {
          amount: json.data.quota / 500000,
          currency: 'USD',
        },
      }
    },

    Login: defineAsyncComponent(() => import('./Login.vue')),
    async logout() {
      await session.delete()
    },

    payment: {
      type: 'qrc',
      currency: 'USD',
      get platform() {
        return t('alipay')
      },
      async create(options) {
        const amount = +options.amount
        const { ok, json } = await proxy('https://aihubmix.com/call/pay/alipay/crt', {
          method: 'POST',
          headers: await makeHeaders(true),
          body: JSON.stringify({
            amount,
            totalAmount: amount * 7.3,
          }),
        })

        if (!ok || !json.success || json.data.code !== '10000') {
          throw new Error(json.data.sub_msg || 'QR code generation failed')
        }

        return {
          orderId: json.data.out_trade_no,
          qrcUrl: json.data.qr_code,
          interval: 3000,
        }
      },
      async check({ orderId }) {
        const { ok, json } = await proxy(`https://aihubmix.com/call/pay/qry/ord?tradeNo=${orderId}`, {
          method: 'GET',
          headers: await makeHeaders(true),
        })

        if (!ok || !json.success) {
          throw new Error('Payment status check failed')
        }

        if (json.data.status === 'WAIT_BUYER_PAY') {
          return 'wait'
        }
        if (json.data.status === 'TRADE_SUCCESS') {
          return 'success'
        }
        return 'canceled'
      },
    },

    baseURL: 'https://aihubmix.com/v1',
    async createKey() {
      const { ok, json } = await proxy('https://aihubmix.com/call/tkn/', {
        method: 'POST',
        headers: await makeHeaders(true),
        body: JSON.stringify({
          name: 'Generated by UniToken',
          subnet: '',
          expired_time: -1,
          models: '',
          unlimited_quota: true,
          remain_quota: -1,
        }),
      })

      if (!ok || !json.success) {
        throw new Error('API Key creation failed')
      }

      return json.data.key
    },

    apis: {
      async login(username: string, password: string) {
        const { ok, headers, json } = await proxy('https://aihubmix.com/call/usr/login', {
          method: 'POST',
          headers: await makeHeaders(false),
          body: JSON.stringify({
            username,
            password,
          }),
        })
        if (!ok || !json.success) {
          throw new Error('Login failed')
        }
        await session.put({
          token: json.data.access_token,
          session: extractSessionFromCookie(headers.get('set-cookie') || ''),
        })
      },

      async register(username: string, password: string) {
        const { ok, headers, json } = await proxy('https://aihubmix.com/call/usr/reg', {
          method: 'POST',
          headers: await makeHeaders(false),
          body: JSON.stringify({
            username,
            password,
            password2: password,
            aff_code: null,
          }),
        })
        if (!ok || !json.success) {
          throw new Error('Registration failed')
        }
        await session.put({
          token: json.data.access_token,
          session: extractSessionFromCookie(headers.get('set-cookie') || ''),
        })
      },
    },
  }
})

function extractSessionFromCookie(cookie: string) {
  const match = cookie.match(/session=([^;]+)/)
  if (!match) {
    throw new Error('Session not found in cookie')
  }
  return match[1]
}
